# Generated by Django 5.1.7 on 2025-03-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('website_type', models.CharField(max_length=100)),
                ('technologies', models.TextField(help_text='JSON-encoded list of technologies')),
                ('features', models.TextField(help_text='JSON-encoded list of features')),
                ('traffic', models.CharField(blank=True, max_length=100)),
                ('idea', models.TextField(blank=True)),
                ('timeline', models.CharField(blank=True, max_length=50)),
                ('maintenance', models.BooleanField(default=False)),
                ('additional_details', models.TextField(blank=True, help_text='JSON-encoded additional details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
